[package]
name = "java_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", features = ["default"] }
once_cell = { version = "1.18.0", features = [] }
zip = { version = "0.6", features = ["zstd"] }
log = "0.4"
env_logger = "0.10"
whoami = "1.4.1"